### ISSUE TITLE
There is an error in the schematics (pdf) of the IP5306 power management SoC

### ISSUE THREAD

**Issue by vicival** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#63]
IP5306's pin 5 (BAT) goes in reality to the R56 - C56 joint.
See the attached picture.
![error_in_IP5306_schematics](https://user-images.githubusercontent.com/37894588/82350110-3861dc80-99fb-11ea-91c7-424b81e140db.png)

**Comment by lewisxhe** [comment]
Feedback has been given, but the notification is correct
![H(MR _1Y~{OD62YQZVF_RAB](https://user-images.githubusercontent.com/22990954/84877942-b9c09380-b0bb-11ea-97f4-0910c3643262.png)

**Comment by nekuneko** [comment]
I don't understand why there are two different shematics for the same IP5306 IC and the R4 resistor's value is different.
![imagen](https://user-images.githubusercontent.com/12543088/117172579-393a7c80-adcc-11eb-8430-8ee866920b42.png)

**Comment by nghia09081999** [comment]
How do I make Vout always output 5V when I want to turn the KEY pin on and off many times?
![image](https://github.com/Xinyuan-LilyGO/LilyGo-T-Call-SIM800/assets/104878648/9bcb0f12-bdfe-44bf-96ea-115565a84e4f)

**Comment by osmany-ferrer** [comment]
Hello there,

My issue has to do with IP5306 battery sensing. LED 4 (100% full) remains blinking forever after battery is charged, as if it does not correctly detect the battery voltage. Wiring is according to the schematic (V1.31) and also the battery is ok because it gets fully charged in another charger.
In version V1.31 of the datasheet,  pin 6 (BAT) is wired to the battery through the resistor R4. However, in version V1.01, pin 6 (BAT) is directly wired to the battery.  I wonder if I should be guided by the previous version?

Thanks in advance for your help,
 Osmany

**Comment by nghia09081999** [comment]
After a while the light will turn off if your circuit is directly connected
to the Battery Cell.

Vào CN, 1 thg 9, 2024 vào lúc 08:42 osmany-ferrer <
***@***.***> đã viết:

**Comment by osmany-ferrer** [comment]
Thanls for your answer. I'll give it a try.
Best bregards,
Osmany
